# Generated by Django 5.2.5 on 2025-09-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPack_Registrar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='family_rep',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
