# Generated by Django 5.2.5 on 2025-09-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPack_Registrar', '0002_family_contact_family_family_rep_family_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registry',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
