# Generated by Django 5.2.5 on 2025-09-19 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPack_Registrar', '0003_registry_gender_registry_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('served', 'Served'), ('rejected', 'Rejected')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xPack_Registrar.registry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
        migrations.DeleteModel(
            name='Packages_rejected',
        ),
        migrations.DeleteModel(
            name='Packages_served',
        ),
    ]
