# Generated by Django 5.2.5 on 2025-09-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xPack_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrar',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='registrar',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='registrar',
            old_name='Password',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='DID',
        ),
    ]
