# Generated by Django 5.2.5 on 2025-09-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPack_App', '0002_rename_contact_registrar_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
