# Generated by Django 5.2.5 on 2025-09-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPack_App', '0003_alter_registrar_contact_alter_registrar_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
