# Generated by Django 5.2.5 on 2025-09-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPack_App', '0005_admincredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrar',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
