# Generated by Django 5.2.5 on 2025-09-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xPack_App', '0006_registrar_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrar',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
